name: Build Nano for Armv7

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget make symlinks

    - name: Configure build
      run: |
        cp -v configs/armv7-2.6.config .config

    - name: Compile Nano
      run: |
        make package/nano/compile V=s